name: CI Workflow for API Integration Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 10:00 UTC from March to November (PDT, UTC-7)
    - cron: '0 10 * 3-11 *'
    # Runs at 11:00 UTC from November to March (PST, UTC-8)
    - cron: '0 11 * 1-3,11,12 *'

jobs:

  Timestamp:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  test-and-publish:
    needs: [ Timestamp ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm eslint .
        # Ensure you have a lint script in your package.json

      - name: Run Tests On Sepolia
        continue-on-error: true
        run: |
          echo "Load environment variables" 
          rm .env && touch .env
          echo API_BASE_URL=${{ secrets.API_BASE_URL }} > .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          test_env=sepolia npx playwright test
      
      - name: Push Slack Notification
        uses: storyprotocol/gha-workflows/.github/workflows/reusable-slack-notifs.yml@main
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          short-desc: "${{ github.repository }}: API Integration Tests have been completed with failed test case(s). Check the results at github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          title: "Playwright Test Results"
          img-url: "http://www.quickmeme.com/img/b9/b9848df257b95cd39585368475a4b4e4a3a8c774f7390226daecb79b912087ad.jpg"
          img-alt-text: "Playwright Test Results"
        secrets:
          channel-name: ${{ secrets.SLACK_CHANNEL_ID_API_INTEGRATION_TESTS }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Upload Test Results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        # if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: sepolia-test-reports
          path: |
            ./playwright-report-sepolia/index.html
